### ISSUE TITLE
Isabel Calabig: Note down chapter timestamps for audio clips and YouTube

### ISSUE THREAD

**Issue by schalkneethling** [mechanical-ink/mycelium-network-podcast#80]
https://drive.google.com/drive/folders/15DUyGimnd5ulyeyHVu7F4RyCB_JPxU2f?usp=drive_link

- [ ] Note down chapter timestamps for audio clips and YouTube

**Comment by schalkneethling** [comment]
@RingDangDoo please add the timestamps here when complete.

**Comment by RingDangDoo** [comment]
Here are the timestamps for Isabel Calabig.

00:00:00 - 00:05:15 - Intro and Dreambox
00:05:15 - 00:09:15 - Challenges of early stage developers
00:09:15 - 00:17:25 - Useful resources
00:17:25 - 00:20:00 - Be weary of traps
00:20:00 - 00:25:55 - Changes in the interview process
00:25:55 - 00:34:50 - Meaning of success and celebrating accomplishments
00:34:50 - 00:38:50 - Recommended resources
00:38:50 - 00:43:02 - In closing

**Comment by schalkneethling** [comment]
> Here are the timestamps for Isabel Calabig.
> 
> 00:00:00 - 00:05:15 - Intro and Dreambox 00:05:15 - 00:09:15 - Challenges of early stage developers 00:09:15 - 00:17:25 - Useful resources 00:17:25 - 00:20:00 - Be weary of traps 00:20:00 - 00:25:55 - Changes in the interview process 00:25:55 - 00:34:50 - Meaning of success and celebrating accomplishments 00:34:50 - 00:38:50 - Recommended resources 00:38:50 - 00:43:02 - In closing

Thanks! It is live - https://www.youtube.com/watch?v=g-aJAHQ4kI0&list=PL8_kr6gR0_x_lXmOPkah53P5D_92o3ue3&index=13
